on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:
    inputs:
      release:
        description: Create a release and publish to crates.io
        required: true
        default: "false"

name: Continuous Integration

jobs:

  test:
    name: Test ${{ matrix.profile.name }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        profile:
        - name: Debug
          arg: ""
        - name: Release
          arg: --release

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: ${{ matrix.profile.arg }}

  release:
    name: Release
    needs: test
    if: github.event.inputs.release == "true"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Publish Crate to crates.io
      uses: actions-rs/cargo@v1
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      with:
        command: publish
        args: --dry-run
    - name: Read Crate Manifest
      id: read_manifest
      run: ${{ github.workspace }}/scripts/ReadCrateManifest.ps1
      shell: pwsh
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.read_manifest.outputs.version }}
        release_name: v${{ steps.read_manifest.outputs.version }}
        draft: true
